set_target_properties(${APP_NAME}
	PROPERTIES PROJECT_LABEL ${PROJECT_NAME}
    VERSION ${WXGIS_VERSION}
    SOVERSION 1
	ARCHIVE_OUTPUT_DIRECTORY ${WXGIS_CURRENT_BINARY_DIR}
    LIBRARY_OUTPUT_DIRECTORY ${WXGIS_CURRENT_BINARY_DIR}
    RUNTIME_OUTPUT_DIRECTORY ${WXGIS_CURRENT_BINARY_DIR} 
    )

#add_custom_target(uninstall
#    COMMAND ${CMAKE_COMMAND} -P ${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake)

if(WIN32)
    install(TARGETS ${APP_NAME} DESTINATION ${WXGIS_CURRENT_BINARY_DIR}/Debug/ CONFIGURATIONS Debug)
    install(TARGETS ${APP_NAME} DESTINATION ${WXGIS_CURRENT_BINARY_DIR}/Release/ CONFIGURATIONS Release)
else()
    install(TARGETS ${APP_NAME}
        RUNTIME DESTINATION bin
        ARCHIVE DESTINATION lib/wxgis
        LIBRARY DESTINATION lib/wxgis)
    install(DIRECTORY ${WXGIS_CURRENT_SOURCE_DIR}/inst/debian/share/ DESTINATION share)
endif() 

